image: percona/everest
catalogSourceName: everest-catalog
catalogSourceTag: latest
telemetry: true
server:
  enabled: true
olm:
  enabled: true
  namespace: everest-olm
vmOperator:
  enabled: true
  namespace: everest-monitoring
  channel: stable-v0
everestOperator:
  enabled: true
  channel: stable-v0
  version: 1.0.1
namespaces:
  - name: everest
    mongodb:
      enabled: true
      channel: stable-v1
    pxc:
      enabled: true
      channel: stable-v1
    pg:
      enabled: true
      channel: stable-v2
