image: percona/everest
telemetry: true
server:
  enabled: true
olm:
  catalogSourceImage: percona/everest-catalog
  enabled: true
  namespace: everest-olm
vmOperator:
  enabled: true
  namespace: everest-monitoring
  channel: stable-v0
everestOperator:
  enabled: true
  channel: stable-v0
namespaces:
  - name: everest
    mongodb:
      enabled: true
      channel: stable-v1
    pxc:
      enabled: true
      channel: stable-v1
    pg:
      enabled: true
      channel: stable-v2
